spring:
    jpa:
        database: H2
        generate-ddl: true
        show-sql: true

datasource:
    article:
        url: jdbc:h2:mem:article
        username: sa
    user:
        url: jdbc:h2:mem:user
        username: sa
